name: Check UpdateID's

on:
  workflow_dispatch:

jobs:
  Archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and install Python
        uses: actions/checkout@v3.5.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies and caching them."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Run Archive script
        id: check_archive_status
        working-directory: updateids
        run: |
          if python ../update.py; then
            echo "Archive script succeeded!"
            echo "success" > ../status.txt
          else
            echo "Archive script failed!"
            echo "failure" > ../status.txt
            exit 1
          fi
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Commit and push changes - updated list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./updateids
          git commit -m "Updated updateid list"
          git push origin ${{ github.ref }}
        continue-on-error: true

      - name: Increment UpdateID in update.py
        run: python ./increment_update.py
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Commit and push changes - update.py
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./update.py
          git commit -m "Incremented UpdateID file in update.py"
          git push origin ${{ github.ref }}
        continue-on-error: false  # Set this to false to stop the workflow if the step fails

      - name: Run Workflow again with next output file
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "workflow_dispatch"}'
        continue-on-error: false  # Set this to false to stop the workflow if the step fails